"""Provider-neutral paths for user-created application data."""

from pathlib import PurePosixPath


USER_DATA_PATH = PurePosixPath("userdata")

# Uploads
UPLOADS_PATH = USER_DATA_PATH / "uploads"
ORIGINAL_UPLOADS_PATH = UPLOADS_PATH / "original"
PNG_UPLOADS_PATH = UPLOADS_PATH / "png"
JPG_UPLOADS_PATH = UPLOADS_PATH / "jpg"
THUMBS320X320_UPLOADS_PATH = UPLOADS_PATH / "thumbs320x320"

# Exports
EXPORTS_PATH = USER_DATA_PATH / "exports"
EXPORTED_SEGMENTATION_PATH = EXPORTS_PATH / "exported-segmentation"
SEGMENTATION_MASK_PATH = EXPORTED_SEGMENTATION_PATH / "mask"
SEGMENTATION_RGB_PATH = EXPORTED_SEGMENTATION_PATH / "rgb"
SEGMENTATION_ZIP_PATH = EXPORTED_SEGMENTATION_PATH / "zip"
EXPORTED_VOCS_PATH = EXPORTS_PATH / "exported-vocs"
EXPORTED_JSONS_PATH = EXPORTS_PATH / "exported-jsons"


STORAGE_DIRECTORIES: tuple[PurePosixPath, ...] = (
    ORIGINAL_UPLOADS_PATH,
    PNG_UPLOADS_PATH,
    JPG_UPLOADS_PATH,
    THUMBS320X320_UPLOADS_PATH,
    SEGMENTATION_MASK_PATH,
    SEGMENTATION_RGB_PATH,
    SEGMENTATION_ZIP_PATH,
    EXPORTED_VOCS_PATH,
    EXPORTED_JSONS_PATH,
)
