# Generated by Django 5.0.6 on 2025-01-27 00:44

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AnnotationType",
            fields=[
                (
                    "annotation_id",
                    models.UUIDField(editable=False, primary_key=True, serialize=False),
                ),
                ("annotation_type", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="ExportDetails",
            fields=[
                (
                    "export_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("zip_file_url", models.CharField(max_length=1000)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImageInfo",
            fields=[
                (
                    "image_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("original_filename", models.CharField(max_length=10000)),
                ("image_width", models.IntegerField()),
                ("image_height", models.IntegerField()),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObjectClass",
            fields=[
                (
                    "class_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("class_name", models.CharField(max_length=50)),
                ("class_index", models.IntegerField()),
                ("color", models.CharField(max_length=7)),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Projects",
            fields=[
                (
                    "project_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project_name", models.CharField(max_length=50)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExportedData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("annotation_file_url", models.CharField(max_length=1000)),
                ("rgb_file_url", models.CharField(max_length=1000, null=True)),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "export_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rest_api.exportdetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Polygons",
            fields=[
                (
                    "polygon_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("points", models.JSONField()),
                ("stability_score", models.FloatField()),
                ("predicted_iou", models.FloatField()),
                (
                    "date_created",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("date_modified", models.DateTimeField(auto_now=True)),
                (
                    "class_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rest_api.objectclass",
                    ),
                ),
                (
                    "image_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rest_api.imageinfo",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="imageinfo",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rest_api.projects"
            ),
        ),
        migrations.AddField(
            model_name="exportdetails",
            name="project_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rest_api.projects"
            ),
        ),
        migrations.CreateModel(
            name="ProjectSetup",
            fields=[
                (
                    "setup_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "annotation_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rest_api.annotationtype",
                    ),
                ),
                (
                    "project_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rest_api.projects",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="objectclass",
            name="setup_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="rest_api.projectsetup"
            ),
        ),
        migrations.CreateModel(
            name="UploadedImage",
            fields=[
                (
                    "upload_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_url", models.CharField(max_length=1000, unique=True)),
                (
                    "image_type",
                    models.CharField(
                        choices=[("JPG", "Jpg"), ("PNG", "Png"), ("THUMB", "Thumb")],
                        max_length=10,
                    ),
                ),
                (
                    "image_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rest_api.imageinfo",
                    ),
                ),
            ],
        ),
    ]
