# Generated by Django 5.0.6 on 2024-06-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationtype',
            name='annotation_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='objectclass',
            name='color',
            field=models.CharField(max_length=7),
        ),
        migrations.AlterField(
            model_name='projects',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
