# Generated by Django 5.0.6 on 2024-08-11 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="imageinfo",
            old_name="image_url",
            new_name="png_image_url",
        ),
        migrations.AddField(
            model_name="imageinfo",
            name="jpg_image_url",
            field=models.CharField(default="null", max_length=1000),
            preserve_default=False,
        ),
    ]
