# Generated by Django 5.0.6 on 2024-06-28 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objectclass',
            name='color',
            field=models.CharField(max_length=7),
        ),
    ]
