# Generated by Django 5.0.6 on 2024-06-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_alter_objectclass_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotationtype',
            name='annotation_id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='projects',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
