# Generated by Django 5.0.6 on 2024-07-08 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_imageupload'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='image_id',
        ),
    ]
