# Generated by Django 5.0.6 on 2024-08-15 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0002_rename_image_url_imageinfo_png_image_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="projects",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
