# Generated by Django 5.0.6 on 2026-08-14 17:46

from django.db import migrations, models


def mark_existing_images_completed(apps, schema_editor):
    """Mark images created before status tracking as already completed."""
    image_info = apps.get_model("rest_api", "ImageInfo")
    image_info.objects.all().update(status="completed")


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0003_alter_polygons_class_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="imageinfo",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("uploaded", "Uploaded"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                    ("canceled", "Canceled"),
                    ("expired", "Expired"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.RunPython(
            mark_existing_images_completed,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
