# Generated by Django 5.0.6 on 2024-09-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0003_alter_projects_description'),
        ('rest_api', '0003_remove_imageupload_image_id'),
    ]

    operations = [
    ]
