# Generated by Django 5.0.6 on 2024-10-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rest_api", "0003_alter_projects_description"),
    ]

    operations = [
        migrations.RenameField(
            model_name="exporteddata",
            old_name="mask_file_url",
            new_name="annotation_file_url",
        ),
        migrations.AlterField(
            model_name="exporteddata",
            name="rgb_file_url",
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
