# Generated by Django 5.0.6 on 2024-09-14 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0004_merge_20240914_1832'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ImageUpload',
        ),
    ]
