# Generated by Django 5.0.6 on 2025-01-12 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0002_alter_polygons_class_id'),
        ('rest_api', '0004_rename_mask_file_url_exporteddata_annotation_file_url_and_more'),
    ]

    operations = [
    ]
