# Generated by Django 5.0.6 on 2025-01-12 00:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_api', '0005_merge_20250112_0031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageinfo',
            name='jpg_image_url',
        ),
        migrations.RemoveField(
            model_name='imageinfo',
            name='png_image_url',
        ),
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('upload_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image_url', models.CharField(max_length=1000, unique=True)),
                ('image_type', models.CharField(choices=[('JPG', 'Jpg'), ('PNG', 'Png'), ('THUMB', 'Thumb')], max_length=10)),
                ('image_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rest_api.imageinfo')),
            ],
        ),
    ]
