name: AnnotatorWebApp

on:
  push:
    branches: [ "emmanuel-branch" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: emmanuel-branch
    # - name: Login Dockerhub
    #   env:
    #     DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
    #     DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
    #   run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker build -t gkishore399/djangoci:latest .
    - name: Push docker image
      run: docker push gkishore399/djangoci:latest
